name: aspics
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4
  - click
  - pyyaml
  - tqdm
  - pyopencl=2022.1
  - pocl
  - numpy=1.22.3
  - python=3.8
  - protobuf = 3.20.0
  # Conda doesn't have some packages
  - pip
  - pip:
    - imgui==1.4.1 
    - glfw==1.12.0
    - PyOpenGL==3.1.6
    - decorator==4.4.2
    - linetimer == 0.1.5
