name: aspics
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.0.3
  - click
  - pyyaml
  - tqdm
  - pyopencl=2020.2.2 
  - pocl
  - numpy=1.18.5
  - python=3.7
  # Conda doesn't have some packages
  - pip
  - pip:
    - imgui==1.4.1 
    - glfw==1.12.0
    - PyOpenGL==3.1.5
    - decorator==4.4.2
