#########################
### ASPICS SIMULATION ###
#########################
microsim:
  study-area: "Manchester"
  iterations: 80 # Number of model iterations (days)
  use-lockdown: FALSE # Whether to preload the lockdown scenario
  start-date: 10 # Counted as number of days since 15/02/2020 (currently, max is 435)
  output: TRUE # Whether to generate output or not
  output-every-iteration: FALSE # Can optionally write output at every iteration, not just at the end
  repetitions: 1 # How many times to run the model
# Parameters that are used to calibrate the model.

microsim_calibration:
  # These multiply the amount of hazard that individuals pass on to shops etc:
  hazard_individual_multipliers:
    presymptomatic: 1.0
    asymptomatic: 0.75 # TODO Lookup testing compliance
    symptomatic: 1.0

  ### PLACES ###
  # Different locations can also have their own multipliers (e.g. to make it easier to pass the disease on to shops than schools)
  # Relevant to calibration in a national modelling scenario
  hazard_location_multipliers:
    Retail: 1.0
    PrimarySchool: 1.0
    SecondarySchool: 1.0
    Home: 1.0
    Work: 1.0 # TODO implement

disease:
  #### DISEASE Parameter #########
  # This multiplies the risk received as individuals visit shops etc.
  current_risk_beta: 0.003 # TODO validate if that is really necessary to get calibrated.

#### INDIVIDUAL Health Conditions Parameters #########
health_conditions:

  sex: # Not need to be calibrated, comes from the literature.
    male_mortality: 1.0
    male_symptomatic: 1.0
    female_mortality: 1.0
    female_symptomatic: 1.0

  type:
    cvd: 1
    diabetes: 1
    bloodpressure: 1
    improve_health: FALSE # TODO can be removed after BMI works

  BMI:
    global_bmi: 1.0 # this one is the one to calibrate.
    white_Ethni_coff1: 5.7
    white_Ethni_coff2: -0.3
    white_Ethni_coff3: 0.0061

    black_Ethni_coff1: 2.340
    black_Ethni_coff2: -0.13
    black_Ethni_coff3: 0.003

    asian_Ethni_coff1: 9.407
    asian_Ethni_coff2: -0.67
    asian_Ethni_coff3: 0.014

    other_Ethni_coff1: 9.21
    other_Ethni_coff2: -0.646
    other_Ethni_coff3: 0.012


  mortality_age:
  # TODO add this categories
  # mortality_probs from params

  symptomatic_age:
    bin_size: 5 #Years per bin
    max_bin_idx: 18 #Largest bin index covers 80+
  # TODO symptomatic_probs

  obesity: # TODO remove this category.
    overweight: 1
    obesity_40: 1.48
    obesity_35: 1.48
    obesity_30: 1.48



#############################
#### Vaccination Status######
#############################

#vaccine_status:
#  not_vaccinated: 0.9
#  first_shot: 0.8
#  second_shot: 0.6
#  third_shot: 0.32

